### ISSUE TITLE
Conversion to rgb32bit

### ISSUE THREAD

**Issue by SangenBR** [Asd-g/AviSynthPlus-RIFE#1]
How do I convert to rgb32bit? I tried it here (z_ConvertFormat(pixel_type="RGBPS", colorspace_op="709:709:709:limited=>rgb:linear:709:full", resample_filter="spline36")) but when I put Rife it ends up closing avspmod

**Comment by Asd-g** [comment]
I don't have issues with your line. Try using `ConvertBits(32, fulls=false, fulld=true)` instead of avsresize.

Btw the RGB shouldn't be linear. This is the correct conversion - `z_ConvertFormat(pixel_type="RGBPS", colorspace_op="709:709:709:limited=>rgb:709:709:full", resample_filter="spline36")`.

**Comment by SangenBR** [comment]
I tried to use the conversion mode you indicated but it gives an error as it is in the image

![planar](https://user-images.githubusercontent.com/42396360/187072834-5956feb8-5003-46ea-b923-833186feea8f.png)

I'm trying like this

```
FFmpegSource2("D:\Users\file.mp4")
ConvertBits(32, fulls=false, fulld=true)
Rife()
```

**Comment by Asd-g** [comment]
Try:
```
FFmpegSource2("D:\Users\file.mp4")
ConvertBits(32, fulls=false, fulld=true)
ConvertToPlanarRGB(matrix="pc709", chromaresample="spline36") # change matrix if it's other
Rife()
```

**Comment by SangenBR** [comment]
the conversion works fine but when active Rife closes avspmod

**Comment by Asd-g** [comment]
What's your avs+ version? It requires AviSynth+ r3682 (can be downloaded from [here](https://gitlab.com/uvz/AviSynthPlus-Builds) until official release is uploaded) or later.

**Comment by SangenBR** [comment]
I'm using the version of this link https://github.com/AviSynth/AviSynthPlus

**Comment by Asd-g** [comment]
You need newer version (for example the one from the link in my previous comment) if you want to use this plugin. It's mentioned in the requirements.

**Comment by SangenBR** [comment]
Ok, thx.
