### ISSUE TITLE
Unknow problem

### ISSUE THREAD

**Issue by rezvalmo** [Asd-g/AviSynthPlus-RIFE#3]
Hi

Someone know how to fix this problem?

I already have avisynthplus 3.7.2 and Microsoft VisualC++2022
Windows 10
Xeon e5 2696 v2
rtx 3060
32gb ram

![unknown](https://user-images.githubusercontent.com/19244984/197902779-e9dce756-90f2-4ca7-b663-5bf45baa8431.png)

**Comment by Asd-g** [comment]
Hi,
What's the exact version of avs+? Type `version()` to see it. From the requirements section of the readme: "AviSynth+ r3682 (can be downloaded from [here](https://gitlab.com/uvz/AviSynthPlus-Builds) until official release is uploaded) (r3689 recommended) or later".

**Comment by DTL2020** [comment]
"how to fix this problem?"

Better to show smallest possible script how to reproduce this crash. Better with internal source like BlankClip() if possible.
