### ISSUE TITLE
Feature Request: Parameter to modify the UHD optical flow process resolution

### ISSUE THREAD

**Issue by Samhayne** [Asd-g/AviSynthPlus-RIFE#5]
I observe that with UHD mode I get much less distortions - but sometimes it still seems like a fixed UHD mode alone is not enough.

Could we get a uhd_scale parameter to modify the process resolution for the optical flow model?
Like the scale parameter described here:
https://github.com/megvii-research/ECCV2022-RIFE

**Comment by Asd-g** [comment]
This looks like feature request for [the rife ncnn library](https://github.com/nihui/rife-ncnn-vulkan).
