### ISSUE TITLE
Can't increase gpu_thread past 2?

### ISSUE THREAD

**Issue by Usulyre** [Asd-g/AviSynthPlus-RIFE#6]
Hi, I can't seem to increase gpu_thread past 2?

I get an error saying this "RIFE: gpu_thread must be between 1 and 2 (inclusive)"

**Comment by Asd-g** [comment]
In this case 2 is the max compute  queue count of your GPU.

**Comment by Usulyre** [comment]
GPU is rx 580 8gb 2048sp

**Comment by Asd-g** [comment]
Run vulkaninfo.exe (it's probably located in ...\Windows\System32). Search for `queueCount` and `queueFlags` with QUEUE_COMPUTE.

**Comment by Usulyre** [comment]
![2023-09-28 08_39_40-Window](https://github.com/Asd-g/AviSynthPlus-RIFE/assets/16013427/dcf42715-0c28-4c59-9383-e187f56d62b0)

Here is that info

**Comment by Asd-g** [comment]
`queueCount` is 2. gpu_thread more than 2 is not supported.

**Comment by Usulyre** [comment]
What's a gpu that can have a gpu_thread of over 8?

**Comment by Asd-g** [comment]
I don't know. Probably some recent GPU from the Enthusiast class.

**Comment by lextra2** [comment]
My AMD RX 6950 XT is also limited to `queueCount = 2` but only ~50% of its compute engine is loaded.
Using `Prefetch(2)` at the end of my avisynth script doubles processing speed and compute engine is now maxed out properly.
