### ISSUE TITLE
Frame blending between scenes

### ISSUE THREAD

**Issue by radpopl** [Asd-g/AviSynthPlus-RIFE#7]
I suggest adding an option (even the default one) so that when changing a scene, you do not copy the last frame, but blend the last frame of the old scene with the first frame of the new scene.
This is what Topaz Video does and it looks pretty good, better than doubling the last frame.

**Comment by Asd-g** [comment]
Isn't what `sc=false` doing?

**Comment by radpopl** [comment]
Yes, rather average :)

![rife-blend](https://github.com/Asd-g/AviSynthPlus-RIFE/assets/11005341/dfb37b8f-73bd-4050-a7aa-33b466a086fc)

**Comment by Asd-g** [comment]
You want the average of the last frame of the old scene and the first frame of the new scene?

**Comment by radpopl** [comment]
Yes. 
![image](https://github.com/Asd-g/AviSynthPlus-RIFE/assets/11005341/e52c9bde-5131-4ff7-b714-6976e2731af4)

**Comment by radpopl** [comment]
> You want the average of the last frame of the old scene and the first frame of the new scene?

The new version of Topaz (Chronos) does it even differently, but I don't know what algorithm it is.

1:
![image](https://github.com/Asd-g/AviSynthPlus-RIFE/assets/11005341/9305ddf0-26a2-4ad8-b772-3fd1a9fea2cc)

2 (intraframe):
![image](https://github.com/Asd-g/AviSynthPlus-RIFE/assets/11005341/6b16dc74-8aae-493d-ad4d-c060ff81a548)

3:
![image](https://github.com/Asd-g/AviSynthPlus-RIFE/assets/11005341/40ee07fb-9ff4-4838-a358-1603012f6b7e)

In any case, in both cases there is no feeling of video chopping.

**Comment by Asd-g** [comment]
You can try the new version `1.2.0`. Parameter `sc1` is added.

**Comment by radpopl** [comment]
Thanks! I will check how it works and write.

**Comment by radpopl** [comment]
It works properly. However, model no. 9 stopped working. (But I don't have the last version of RIFE from 3 weeks ago yet). I also noticed that the newly generated frames are slightly brighter.
Normally it makes no difference, but when several are generated (via RIFE(), RIFE(), RIFE()), the middle one is clearly brighter (this can be seen in the histogram). I will make an entry when I generate screenshots.
